### ISSUE TITLE
Email address not corrected if entered with the API

### ISSUE THREAD

**Issue by ErikHommel** [JohnFF/Email-Amender#8]
Hi John, just checking your email amend extension for Amnesty International Vlaanderen
Really nice, we will use it.

There is an additional requirement though, as they also have a lot of data coming in from outside through the API. And I have tested but I can still add invalid email addresses with the API.

First of all: is that your expectation too? If so, I would like to add a scheduled job that corrects existing email addresses with the same pattern. Ideally I would like to add that to your extension so if you agree I am going to do a PR

**Comment by JohnFF** [comment]
Hi Erik,

If possible I'd like to establish why they aren't being corrected. E.g.,
are they not triggering the hook, do we need a different hook etc?

In my mind, a scheduled job wouldn't be the best way to go - instant or
not at all. Otherwise you're fiddling with epople's data without their
knowledge. Let's get the API hook working.

John

**Comment by ErikHommel** [comment]
Agree, I will investigate why the hook is not triggered with the API. Not yet though as this will become effective when we move to 4.7 (expected April 2018)

**Comment by JohnFF** [comment]
Agreed, also, make sure you've checkedbthe settings page, incl ticking the
auto correct box. And let me know what email address you're testing with.

**Comment by JohnFF** [comment]
@ErikHommel - I just saw this was still open. There's a unit test protecting this, proving in my view that it works. Please let me know if you can reproduce this issue with the Automatic Correction setting enabled.
